create table SPRINGSEC_USER (id bigint generated by default as identity (start with 1), username varchar(255), password varchar(255), roles varchar(255), primary key (id));
insert into SPRINGSEC_USER (id, username, password, roles) values (default, 'admin', '1844156d4166d94387f1a4ad031ca5fa', 'ADMIN')
insert into SPRINGSEC_USER (id, username, password, roles) values (default, 'user', 'd781eaae8248db6ce1a7b82e58e60435', 'USER')
